config/routes.rb
Rails.application.routes.draw do
  devise_scope :admin do
	authenticated :admin do
		root 'cashiers#index'
		resources :cashiers, :products
		put 'deactivate/:id(:format)', :to => 'cashiers#deactivate', :as => :deactivate_cashier
		put 'activate/:id(:format)', :to => 'cashiers#activate', :as => :activate_cashier
		put 'deactivate_product/:id(:format)', :to => 'products#deactivate', :as => :deactivate_product
		put 'activate_product/:id(:format)', :to => 'products#activate', :as => :activate_product
	end
  end
  devise_scope :cashier do
	authenticated :admin do
		root 'orders#new'
	end
  end
  devise_for :cashiers, controllers: {
    sessions:           "cashiers/sessions",
    passwords:          "cashiers/passwords",
    confirmations:      "cashiers/confirmations",
  }
  resources :orders
  devise_for :admins
  root 'welcome#home'
  get 'checkpoint/', :to => 'welcome#checkpoint', :as => :checkpoint
  post 'checkpoint/', :to => 'welcome#verify', :as => :verify
  get 'dailyreport', :to => 'orders#report', :as => :report
  get 'cashierreport/:id', :to => 'orders#cashierreport', :as => :cashierreport
  post 'orders/summary', :to => 'orders#summary', :as => :orders_summary
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
  def checkpoint
  end
  def verify
  	@display = true 
  	if test_dump[:name] == nil
  		@display = true
  		render 'cashiers/sessions/new'
  	else
				@check = Cashier.find_by_name(test_dump[:name])
				if @check == nil
					render 'home'
				else
					if @check.active == true
						@item = @check.email
						@display = false
						render 'cashiers/sessions/new'
					else
						render 'home'
					end
				end
			end
  #When you wake up, remember to make this controller check if name exists, if user is active, and if both are met, pass values
  #to the sessions controller to ensure that the email is passed bc devise sucks at username auth
  end
  private
	def test_dump
			params.require(:query).permit(:name)
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/checkpoint.html.erb
	<%= form_for :query, url: verify_path do |f| %>
<div class="login_div text-center">
<div class="card">

	  <%= image_tag("login", class: "card-img-top", style: "height: 5%") %>
	  <div class="card-block">
	    <h3 class="card-title">Cashier Login</h3>
	    <p class="card-text"><%= f.text_field :name, placeholder: "Enter username"%></p>
	  </div>
	  <div class="card-block">
	    <%= f.submit 'Proceed' %>
	    <br>
	    <hr>
	    <%= link_to 'Login with email', new_cashier_session_path %>
	    
	  </div>
	</div>
</div>
</div>
<% end %>

app/views/welcome/home.html.erb

<div class="homepage text-center">
    <h2 class="">The minimalist approach to maximizing profit.</h2>
    <h5><%= link_to('Cashiers', checkpoint_path)  %> | <%= link_to('Administrators', new_admin_session_path)  %></h5>
    <%= image_tag("boxes", style: "height: 5%", :size => '186x1000') %>

</div>