config/routes.rb
Rails.application.routes.draw do
  devise_scope :admin do
	authenticated :admin do
		root 'cashiers#index'
		resources :cashiers, :products
		put 'deactivate/:id(:format)', :to => 'cashiers#deactivate', :as => :deactivate_cashier
		put 'activate/:id(:format)', :to => 'cashiers#activate', :as => :activate_cashier
		put 'deactivate_product/:id(:format)', :to => 'products#deactivate', :as => :deactivate_product
		put 'activate_product/:id(:format)', :to => 'products#activate', :as => :activate_product
	end
  end
  devise_scope :cashier do
	authenticated :admin do
		root 'orders#new'
	end
  end
  devise_for :cashiers, controllers: {
    sessions:           "cashiers/sessions",
    passwords:          "cashiers/passwords",
    confirmations:      "cashiers/confirmations",
  }
  resources :orders
  devise_for :admins
  root 'welcome#home'
  get 'checkpoint/', :to => 'welcome#checkpoint', :as => :checkpoint
  post 'checkpoint/', :to => 'welcome#verify', :as => :verify
  get 'dailyreport', :to => 'orders#report', :as => :report
  get 'cashierreport/:id', :to => 'orders#cashierreport', :as => :cashierreport
  post 'orders/summary', :to => 'orders#summary', :as => :orders_summary
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cashier.rb
class Cashier < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthables
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	  devise :database_authenticatable, :registerable,
			 :recoverable, :rememberable, :trackable, :validatable
	  belongs_to :admin
	  has_many :orders
	  validates :name, presence: true, uniqueness: true
  	def deactivate
		update_attribute :active,false
	end
	def activate
		update_attribute :active,true
	end
end

app/controllers/cashiers/confirmations_controller.rb
class Cashiers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/cashiers/omniauth_callbacks_controller.rb
class Cashiers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/cashiers/passwords_controller.rb
class Cashiers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/cashiers/registrations_controller.rb
class Cashiers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
	super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/cashiers/sessions_controller.rb
class Cashiers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new 
	super
  end

  # POST /resource/sign_in
  def create 
	super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/cashiers/unlocks_controller.rb
class Cashiers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/cashiers_controller.rb
class CashiersController < ApplicationController
	before_action :authenticate_admin!
 	def new
	end
	def show
		@cashier = Cashier.find (params[:id])
	end
	def create
		@cashier = current_admin.cashiers.new(param_drop)
		@cashier.adder = current_admin.email
		@cashier.admin = current_admin
		@cashier.active = true
		@cashier.password = "default"
		var = @cashier.name
		@cashier.email = var +"@cashier.com"
		@cashier.save
		redirect_to @cashier
	end
	def edit
		@cashier = Cashier.find(params[:id])
	end
	def update
		@cashier = Cashier.find(params[:id])
		if @cashier.update(param_drop)
			@cashier.encrypted_password = param_drop[:password]
			redirect_to @cashier
		else
			redirect_to cashiers_path
		end
	end
	def activate
		@cashier = Cashier.find(params[:id])
		@cashier.activate
		redirect_to cashiers_path
	end
	def deactivate
		@cashier = Cashier.find(params[:id])
		@cashier.deactivate
		redirect_to cashiers_path
	end
	def index
		@cashiers = Cashier.all
	end
	private
		def param_drop
			params.require(:cashier).permit(:name,:active,:email,:password)
		end
end

app/helpers/cashiers_helper.rb
module CashiersHelper
end

app/views/cashiers/edit.html.erb
<div class="row">
	<div class="col-1"></div>
	<div class="col-4">
		<h3 class="display-4"> New Cashier </h3>
	</div>
</div>
<hr>
<br>
<%= form_for @cashier do |cashier| %>
<div class="row">
	<div class="col-4">
		<div class= row>
			<div class="col-3"></div>
			<div class="col-3">	<%= cashier.label :name %> </div>
			<div class="col-6"> <%= cashier.text_field :name %></div>
		</div>
		<br>
		<div class= row>
			<div class="col-3"></div>
			<div class="col-3">	<%= cashier.label :email %></div>
			<div class="col-6"> <%= cashier.text_field :email %></div>
		</div>
		<br>
		<div class= row>
			<div class="col-3"></div>
			<div class="col-3">	<%= cashier.label :password %></div>
			<div class="col-6"> <%= cashier.text_field :password %></div>
		</div>
		<br>
		<div class= row>
			<div class="col-3"></div>
			<div class="col-3">	<b> Note </b> </div>
			<div class="col-6"> Usernames are unique. <br> Default password is "default" </div>
		</div>
		<br>
		<div class= row>
			<div class="col-3"></div>
			<div class="col-3"><%= cashier.submit:Submit, class: 'btn btn-secondary' %></div>
			<div class="col-6"><%= link_to "<button type=\"button\" class=\"btn btn-secondary\">View All Cashiers</button>".html_safe,cashiers_path %></div>
		</div>
	</div>
	<div class="col-8">
	</div>
</div>
<% end %>

app/views/cashiers/index.html.erb
<% if @cashiers == nil %>
		No Cashiers added. Add cashier:
<% else %>
		<div class="container">
		<h3 class="display-4"> All Cashiers</h3>
		<%= link_to "New Cashier", new_cashier_path %>
		<hr>
		<table class= "table table-hover">
			<thead>
			<tr>
				<th> Name </th>
				<th> Admin </th>
				<th> Status </th>
				<th> View link </th>
				<th> Edit link </th>
				<th> </th>
			</tr>
			</thead>
				<% @cashiers.each do |cashier|%>
					<tr>
						<td> <%= cashier.name %> </td>
						<td> <%= cashier.adder %> </td>
						<% if cashier.active == true %>
							<td> ACTIVE </td>
						<% else %>
							<td> INACTIVE </td>
						<% end %>
						<td> <%= link_to "View", cashier_path(cashier) %> </td>
						<td> <%= link_to "Edit", edit_cashier_path(cashier) %> </td>
						<td class="text-center"> 
							<% if cashier.active == true %>
								<%= link_to "<button type=\"button\" class=\"btn btn-secondary\">Deactivate?</button>".html_safe, deactivate_cashier_path(cashier), method: :put, data: { confirm: "Are you sure?" }%>
							<% else %>
								<%= link_to "<button type=\"button\" class=\"btn btn-secondary\">Activate?</button>".html_safe, activate_cashier_path(cashier), method: :put, data: { confirm: "Are you sure?" } %>
							<% end %>
						</td>
					</tr>
				<% end %>	
		</table>
<% end %>
</div>

app/views/cashiers/new.html.erb
<div class="row">
	<div class="col-1"></div>
	<div class="col-4">
		<h3 class="display-4"> New Cashier </h3>
	</div>
</div>
<hr>
<br>
<%= form_for :cashier, url: cashiers_path do |cashier| %>
<div class="row">
	<div class="col-4">
		<div class= row>
			<div class="col-3"></div>
			<div class="col-3">	<%= cashier.label :name %> </div>
			<div class="col-6"> <%= cashier.text_field :name %></div>
		</div>
		<br>
		<div class= row>
			<div class="col-3"></div>
			<div class="col-3">	<b> Note </b> </div>
			<div class="col-6"> Usernames are unique. <br> Default password is "default" </div>
		</div>
		<br>
		<div class= row>
			<div class="col-3"></div>
			<div class="col-3"><%= cashier.submit:Submit, class: 'btn btn-secondary' %></div>
			<div class="col-6"><%= link_to "<button type=\"button\" class=\"btn btn-secondary\">View All Cashiers</button>".html_safe,cashiers_path %></div>
		</div>
	</div>
	<div class="col-8">
	</div>
</div>
<% end %>
</div>

app/views/cashiers/show.html.erb
<div class="container">
<br>
<h3 class='display-4'><%= @cashier.name %> </h3>
Cashier # <%= @cashier.id %>
<hr>
<b>Status</b> 
<% if @cashier.active = true %>
    ACTIVE
<% else %>
    INACTIVE
<% end %>
<br>

<br>
    <b>Email</b> <%= @cashier.email %>
<hr>
<%= link_to "<button type=\"button\" class=\"btn btn-secondary\"> Edit </button>".html_safe, edit_cashier_path(@cashier) %>
<%= link_to "<button type=\"button\" class=\"btn btn-secondary\">View All Cashiers</button>".html_safe, cashiers_path %>
</div>
</div>