config/routes.rb
Rails.application.routes.draw do
  devise_scope :admin do
	authenticated :admin do
		root 'cashiers#index'
		resources :cashiers, :products
		put 'deactivate/:id(:format)', :to => 'cashiers#deactivate', :as => :deactivate_cashier
		put 'activate/:id(:format)', :to => 'cashiers#activate', :as => :activate_cashier
		put 'deactivate_product/:id(:format)', :to => 'products#deactivate', :as => :deactivate_product
		put 'activate_product/:id(:format)', :to => 'products#activate', :as => :activate_product
	end
  end
  devise_scope :cashier do
	authenticated :admin do
		root 'orders#new'
	end
  end
  devise_for :cashiers, controllers: {
    sessions:           "cashiers/sessions",
    passwords:          "cashiers/passwords",
    confirmations:      "cashiers/confirmations",
  }
  resources :orders
  devise_for :admins
  root 'welcome#home'
  get 'checkpoint/', :to => 'welcome#checkpoint', :as => :checkpoint
  post 'checkpoint/', :to => 'welcome#verify', :as => :verify
  get 'dailyreport', :to => 'orders#report', :as => :report
  get 'cashierreport/:id', :to => 'orders#cashierreport', :as => :cashierreport
  post 'orders/summary', :to => 'orders#summary', :as => :orders_summary
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	def deactivate
		update_attribute :status,false
	end
	def activate
		update_attribute :status,true
	end
	has_many :orderlines
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :authenticate_admin!
	def index
		@products = Product.all
	end
	def new
	end
	def show
		@product = Product.find(params[:id])
	end
	def create
		@product = Product.new(param_drop)
		@product.status = 'true'
		if @product.save
			redirect_to products_path
		else 
			render 'new'
		end
	end
	def activate
		@product = Product.find(params[:id])
		@product.activate
		redirect_to products_path
	end
	def deactivate
		@product = Product.find(params[:id])
		@product.deactivate
		redirect_to products_path
	end
	def edit
		@product = Product.find(params[:id])
	end
	def update
		@product = Product.find(params[:id])
		if @product.update(param_drop)
			redirect_to @product
		else
			redirect_to products_path
		end
	end
	private
		def param_drop
			params.require(:product).permit(:name,:price,:status, :discount, :description)
		end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<div class="row">
	<div class="col-1"></div>
	<div class="col-4">
		<h3 class="display-4"> Edit Product </h3>
	</div>
</div>
<hr>
<%= form_for @product do |product| %>
<div class="row">
	<div class="col-4">
		<div class= row>
			<div class="col-3"></div>
			<div class="col-3"><%= product.label :name %></div>
			<div class="col-6"><%= product.text_field :name %></div>
		</div>
		<br>
		<div class= row>
			<div class="col-3"></div>
			<div class="col-3"><%= product.label :price %></div>
			<div class="col-6"><%= product.text_field :price %></div>
		</div>
		<br>
		<div class= row>
			<div class="col-3"></div>
		<div class="col-3"><%= product.label :discount %></div>
		<div class="col-6"><%= product.text_field :discount %></div>
		</div>
		<br>
		<div class= row>
		<div class="col-3"></div>
		<div class="col-3"><%= product.label :description %></div>
		<div class="col-6"><%= product.text_area :description %></div>
		</div>
		<br>
		<div class= row>
		<div class="col-3"></div>
		<div class="col-3"><%= product.submit %></div>
		<div class="col-6"></div>
		</div>
	</div>
	<div class="col-8">
	</div>
</div>
<% end %>

app/views/products/index.html.erb
<div class="container">
	<br>
	<h3 class="display-4"> All Products </h3>
	<%= link_to "New Product", new_product_path %>
	<hr>
	<% if @products.length == 0 %>
			No products added. Add product:
	<% else %>
			<table class="table table-hover">
				<thead>
					<tr>
						<th> Name </th>
						<th> Price </th>
						<th> Status </th>
						<th></th>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<% @products.each do |product| %>
					<tr>
						<td><%= product.name %></td>
						<td><%= "%.2f"%product.price %></td>
						<% if product.status == true %>
							<td> ACTIVE </td>
						<% else %>
							<td> INACTIVE </td>
						<% end %>
						<td> <%= link_to "View", product_path(product) %> </td>
						<td> <%= link_to "Edit", edit_product_path(product) %> </td>
						<td class="text-center"> 
								<% if product.status == true %>
									<%= link_to "<button type=\"button\" class=\"btn btn-secondary\">Deactivate?</button>".html_safe, deactivate_product_path(product), method: :put, data: { confirm: "Are you sure?" } %>
								<% else %>
									<%= link_to "<button type=\"button\" class=\"btn btn-secondary\">Activate?</button>".html_safe, activate_product_path(product), method: :put, data: { confirm: "Are you sure?" } %>
								<% end %>
						</td>
					</tr>
				<% end %>
			</table>
	<% end %>
</div>

app/views/products/new.html.erb
<div class="row">
	<div class="col-1"></div>
	<div class="col-4">
		<h3 class="display-4"> New Product </h3>
	</div>
</div>
<hr>
<%= form_for :product, url: products_path do |product| %>
<div class="row">
	<div class="col-4">
		<div class= row>
			<div class="col-3"></div>
			<div class="col-3"><%= product.label :name %></div>
			<div class="col-6"><%= product.text_field :name %></div>
		</div>
		<br>
		<div class= row>
			<div class="col-3"></div>
			<div class="col-3"><%= product.label :price %></div>
			<div class="col-6"><%= product.text_field :price %></div>
		</div>
		<br>
		<div class= row>
			<div class="col-3"></div>
		<div class="col-3"><%= product.label :discount %></div>
		<div class="col-6"><%= product.text_field :discount %></div>
		</div>
		<br>
		<div class= row>
		<div class="col-3"></div>
		<div class="col-3"><%= product.label :description %></div>
		<div class="col-6"><%= product.text_area :description %></div>
		</div>
		<br>
		<div class= row>
		<div class="col-3"></div>
		<div class="col-3"><%= product.submit %></div>
		<div class="col-6"></div>
		</div>
	</div>
	<div class="col-8">
	</div>
</div>
<% end %>

app/views/products/show.html.erb
<div class="container">
<br>
<h3 class='display-4'><%= @product.name %></h3>
<hr>
<b>Status</b> 
<% if @product.status = true %>
    ACTIVE
<% else %>
    INACTIVE
<% end %>
<br>
<% if @product.discount != nil %>
    <b>Discount</b> <%= @product.discount*100 %> %
<% end %>
<br>
    <b>Price</b> <%= "%.2f"%@product.price %>
<hr>
<b>Description</b>
<br>
<p>
    <%= @product.description %>
</p>
<hr>
<%= link_to "<button type=\"button\" class=\"btn btn-secondary\"> Edit </button>".html_safe, edit_product_path(@product) %>
<%= link_to "<button type=\"button\" class=\"btn btn-secondary\">View All Products</button>".html_safe, products_path %>
</div>
</div>