config/routes.rb
Rails.application.routes.draw do
  devise_scope :admin do
	authenticated :admin do
		root 'cashiers#index'
		resources :cashiers, :products
		put 'deactivate/:id(:format)', :to => 'cashiers#deactivate', :as => :deactivate_cashier
		put 'activate/:id(:format)', :to => 'cashiers#activate', :as => :activate_cashier
		put 'deactivate_product/:id(:format)', :to => 'products#deactivate', :as => :deactivate_product
		put 'activate_product/:id(:format)', :to => 'products#activate', :as => :activate_product
	end
  end
  devise_scope :cashier do
	authenticated :admin do
		root 'orders#new'
	end
  end
  devise_for :cashiers, controllers: {
    sessions:           "cashiers/sessions",
    passwords:          "cashiers/passwords",
    confirmations:      "cashiers/confirmations",
  }
  resources :orders
  devise_for :admins
  root 'welcome#home'
  get 'checkpoint/', :to => 'welcome#checkpoint', :as => :checkpoint
  post 'checkpoint/', :to => 'welcome#verify', :as => :verify
  get 'dailyreport', :to => 'orders#report', :as => :report
  get 'cashierreport/:id', :to => 'orders#cashierreport', :as => :cashierreport
  post 'orders/summary', :to => 'orders#summary', :as => :orders_summary
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>POS</title>
    <%= csrf_meta_tags %>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% stylesheet_link_tag "style" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
<nav class = "navbar navbar-toggleable-md navbar-light bg-faded navbar-fixed-top navbar-custom" role = "navigation">
  <a class="navbar-brand sellpoint" href="#">SELLPOINT></a>
				<ul class="navbar-nav mr-auto">
				  <li class="nav-item"> <%= link_to 'HOME', root_path,class: 'nav-link' %> </li>
				  <% if admin_signed_in? == true %>
					<li class="nav-item">
						<%= link_to "CASHIERS",cashiers_path, class: 'nav-link' %>
					</li>
					<li class="nav-item dropdown">
						<%= link_to "PRODUCTS",products_path, class: 'nav-link' %>
					</li>
					<li class="nav-item">
						<%= link_to "REPORT", report_path,class: 'nav-link' %>
					</li>
				  <% end %>
				  
				  <% if cashier_signed_in? == true %>
						<li class="nav-item">
							<%= link_to 'ADD ORDER', new_order_path, class: 'nav-link' %>
						</li>
						<li class="nav-item">
							<%= link_to 'DAILY SUMMARY', cashierreport_path(current_cashier), class: 'nav-link' %>
						</li>
						<li class="nav-item">
							<%= link_to 'ALL ORDERS', orders_path, class: 'nav-link' %>
						</li>
				   <% end %>
				</ul>
				<% if cashier_signed_in? == true %>
						<ul class="nav navbar-nav navbar-right">
							<li class="nav-item">
						  	<a href='#'  class= 'nav-link disabled' > Logged in as <%= current_cashier.name %> </a>
							</li>
							<li class="nav-item">
							  <%= link_to 'Logout', destroy_cashier_session_path, method: :delete, class: 'nav-link' %>  
							</li>
						</ul>
				<% end %>
				<% if admin_signed_in? == true %>
					<ul class="nav navbar-nav navbar-right">
						<li class="nav-item">
							<a href='#' class='nav-link disabled'> Logged in as <%= current_admin.email %> </a>
						</li>
						<li class="nav-item">
							<%= link_to 'Logout?', destroy_admin_session_path, method: :delete, class: 'nav-link' %>        
						</li>
						<li class="nav-item">
							
						</li>
					</ul>
				<% end %>
</nav>
<hr>
	<p class="notice"><%= notice %> </p>
	<p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>